export enum SessionFlow {
  AWAITING_LOCATION = 'AWAITING_LOCATION',
  AWAITING_QUOTE_SELECTION = 'AWAITING_QUOTE_SELECTION',
  AWAITING_QUOTE_RESPONSE = 'AWAITING_QUOTE_RESPONSE',
  PHARMACY_REGISTRATION = 'PHARMACY_REGISTRATION',
  CUSTOMER_REGISTRATION = 'CUSTOMER_REGISTRATION',
  AWAITING_PHARMACY_LOCATION = 'AWAITING_PHARMACY_LOCATION',
}
